Add Glossary to Documentation
hyperledger-iroha/iroha-dco pull request #1155
Opened 2018-03-29 17:09 UTC by igor-egorov

### Description of the Change

This pr introduces the new version of Glossary.

### Benefits

It will be easier to get familiar with Iroha for everyone.

### Possible Drawbacks 

The contents of Core Concepts page becomes a subject of change.

2018-03-29 20:57 UTC, l4l requested changes
No definitons of block, commit (or committed block) and signatory

2018-03-30 08:12 UTC, neewy commented
Since Igor is not available, I am correcting his code according to review changes

2018-03-30 08:17 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +An abstraction that represents users of Iroha.
Exactly

2018-03-30 08:45 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +Command is a request to Iroha that **does** change the `state <#world-state-view>`__.
it is for an emphasis, it is okay. compare that to a query

2018-03-30 08:45 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +All modifications are performed via commands.
ambiguous

2018-03-30 09:01 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +If there are missing blocks, they will be downloaded from another peers via `Synchronizer <#synchronizer>`__.
That is still okay :) let it be please

2018-03-30 09:07 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +
That is okay :)

2018-03-30 09:31 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +Is a part of `consensus <#consensus>`__.
🙃

2018-03-30 09:31 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +See `Verified Proposal Creator <#verified-proposal-creator>`__.
🙃

2018-03-30 09:31 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +A node that is a part of cluster running Iroha.
done

2018-03-30 09:32 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +A node that is a part of cluster running Iroha.
done

2018-03-30 09:36 UTC, l4l commented on docs/source/core_concepts/glossary.rst
> +All modifications are performed via commands.
otherwise quite vague, it may mean modification of the client state

2018-03-30 09:55 UTC, l4l approved these changes

2018-03-30 09:55 UTC, l4l commented on docs/source/core_concepts/glossary.rst
> +whereas in Iroha a client interacts with any peer similarly to a single server.
is it ok that it's at the new line?

2018-03-30 09:55 UTC, l4l commented on docs/source/core_concepts/glossary.rst
> +A consensus algorithm is a process in computer science used to achieve agreement on a single data value among distributed processes or systems. Consensus algorithms are designed to achieve reliabilit
algorithm cannot be a process, it is a ordered set of steps/instruction/whatever you like

2018-03-30 09:55 UTC, l4l commented on docs/source/core_concepts/glossary.rst
> +A consensus algorithm is a process in computer science used to achieve agreement on a single data value among distributed processes or systems. Consensus algorithms are designed to achieve reliabilit
does `--` rendered properly (like a long `-`)?

2018-03-30 09:56 UTC, neewy commented on docs/source/core_concepts/glossary.rst
> +whereas in Iroha a client interacts with any peer similarly to a single server.
yes

2018-03-30 10:00 UTC, muratovv approved these changes

2018-03-30 10:00 UTC, muratovv commented on docs/source/core_concepts/glossary.rst
> +Command is a request to Iroha that **does** change the `state <#world-state-view>`__.
A command is not a request by itself. It is an intention to change.

2018-03-30 10:00 UTC, muratovv commented on docs/source/core_concepts/glossary.rst
> +The main goal of PCS is to hide the complexity of interaction with consensus implementation from `Torii <#torii>`__.
There is no reason to make a clarification about Torii.

2018-03-30 10:00 UTC, muratovv commented on docs/source/core_concepts/glossary.rst
> +Uses gRPC as a transport.
Is it possible to make a link for client libraries here?

2018-03-30 10:00 UTC, muratovv commented on docs/source/core_concepts/glossary.rst
> +Uses gRPC as a transport.
Also for the protobuf schema.

2018-03-30 10:00 UTC, muratovv commented on docs/source/core_concepts/glossary.rst
> +Represents all checks that do not depend on `World State View <#world-state-view>`__.
Just say that object is well-formed including signatures.

2018-03-30 10:11 UTC, merged